---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-client-secret
  namespace: dex
spec:
  encryptedData:
    dexAppSecret: AgBe/UAFvl27OEdZ5T6C42GyeDW0wZvZJaOzr2hArq/dY0q+LUZESdX2ECEAvzA9+ZCBwVZ0C1o8fp5+DTMRM5lLrPrYXamYFXEY2en5JS9myuqHPycwsLO38i2A5LfS4yYolZoxKQrIW1Gpg1t8e/vr4RWP9b1jqnR3DGOhdC9HPihLIdNoOpVXWw9Cx7CTAJqsN0cRfDUC5Qcba0BS58s7IaqmV6OnSASOTnoSfPjPI6Ek45CAjhGAxGexPxrnLQFJQP5y+oXtZSqGW0roT2smj9xEOqBhKP1dP+oGCi58q/c4WnnL92I2E2FprPJbUKLBjLLaN8OTTln6cgurwip/UVrNa6veDXK/gQW6JTutSl0P7gaywzWu/tHxOWjIJ70GiSyBqr6/GzlbSWQ2fLGFkR++W8pj5GPs3YMpifqeiBoOq3HHLS7h0mTZ7Avara+al8/QnRc81Lrhz1xM153CVy9wF8DnOwPKpiixMSHfVVRNEaP0vKnM7o1EM/oy+jcuCNYNW7bDG68sNWcu7aCSQbvYshnCxlBl+7v1r5ecu/IhHCdYjtUNDBe/N+0vqezcgeMJu6BVtbtFk+spvXP4fw0l9grP1yKTLCljKDa39RZr6Lvrk8DROIVoWvFmqo9vEyd3T731Ct+Sa9RSaA4MDC22rHiG/RwPyRU/nsuaf03N2p0ReboBj8wl7UOQMQ2HK2AQ9E23R0zk3l07keqTDWPWQ5YDpX/g5efqIMJ3G8vQ2pFLzwUgJybXbdXa6FH3yigi5f6kk4cL1yJw+c66
  template:
    metadata:
      creationTimestamp: null
      name: dex-client-secret
      namespace: dex
    type: Opaque
