---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: dex
spec:
  encryptedData:
    clientSecret: AgBNKOj5uzPCIT6oD6D7B367K9ObLcUG9LgdjwmEFh1q3fFAG47Oukm545LKFVu+CYVH2ZnvtBQhyq0y0VRUAn5fuDYTrips1BVV2bpc1NgHGW5C3Bn4IXFbdFnL0Oa3xGdoNukq21SJIuoImfcOrATqBqcN8UQN4Zsn1wzI7ulus6ghvN+fEswLsJ2iad5AeXEJ3hTqvBjpVsLWCp+gY3VIkTgOFPJ6J7aTVmCqHooaaUO4X3dcTX1grt6ebG04loRoJtjTQlCTZcM9WJCP86j5sQv3M5ZhEFX2C747YE8WV8PI92CgrkZRnXqF4DqiJ68UmbR01vo2AygFFrSrmte6VgAWOMAviZ14Q3F3uZsoDNtNghSPXir6pTVFnzbSNGD9AQXfXoR5GUBW1mAgyh+JrEMUCAXpJM9YUJF8iobuagwYRa+kKQCPlkc8o4Ig5NTzM++dBNnDz+5oX1MXE0OOId9O+mG6pRSKJActOJwp2BCoV3n0fjDar6+jyuNt2ef/r+yjEncuFpb1b92p/jc10EvgHyZ9ysdHsBBXBMVQ7t4vH/GKn9Fxu2yjCx/qzGxpfKvMQhnLh6jHifDw4SbQ/eyicCqg3rBGoK+79W6AJ8aEri+TymYjEu2LVzgZT35H1Q8NxlPgJ7hXiYHsm6cxfYU6Bu6L9zyI1KkqtJPP8+40LKdH2efCQ8epyI8hYevINuqiRD0quTpIso5uAbsuwOGbvFTtk8jypIbr45R3/cDaNZTQGewn
  template:
    metadata:
      creationTimestamp: null
      name: github-client-secret
      namespace: dex
    type: Opaque
