config:
  issuer: https://dex.hana.ishiori.net/dex
  storage:
    type: kubernetes
    config:
      inCluster: true
  oauth2:
    skipApprovalScreen: true
  staticClients:
  - id: dex-k8s-client
    redirectURIs:
    - 'http://localhost:5555/apis/auth/callback' # Local Development
    - 'https://login.hana.ishiori.net/apis/auth/callback' # Hana
    name: 'Dex Kubernetes Client'
    secretEnv: DEX_APP_CLIENT_SECRET
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: Ov23liOmRkvwnR0DICXc
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: https://dex.hana.ishiori.net/dex/callback
      orgs:
      - name: ishiori-net
        teams:
        - netwide-admin
        - hana-maintainer
        - hana-developer
      teamNameField: slug
      useLoginAsID: true

envVars:
  - name: GITHUB_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: github-client-secret
        key: clientSecret
  - name: DEX_APP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: dex-client-secret
        key: dexAppSecret