---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgDQGGQ+jnmc4QjQzxNw/aFgpTicNu99mrK3c60ytVUUKdp9HSsEoWZ3mLRHTT/P1c9er2hBYcB8BXKsS69YUM1ZbF/nsdN39re4v8FqJBZGQ3nZmr3NuWT3mSDS5+qeydUhNFojk3M9P3It0LoEcjouVNIU6dgdeMy64VbzOcP9zIdcML5o92QI80PIflRgn+G+uZ+fGh6s9exQKVS4iDv6byVifxOPNjRkBJHFW5AwRfeGen+YwBtuKT0jwJePFDQUhw6m4R0do/biuxGe67uG71YbJfz0lMCDrht5I8B53PFfomBqhoUJWKYF8JzC44z1n0u51Sfb2zyV/k7SLZo9qPDcYI60KJ283BbU8lbc7DvUFBVt7UFWvbxzWhNcADVb738pOBsPpJ3FHykxJJ9O+bIDJdzUIaKf2c5ZTmXr5dNOQJi761pW7GJyGL2gnu+MDStHF0lRQIZMW/ToIaWXAGwVm/tJRXZgN2R/dx89bkjxKHt/SnPMTTp+M/sGFynLRvqDzKjY2QB6oPtjmB7u93hgDZAGZwJMbC0GCBzCnAcEEkf30X5JN447MLtuKDcQRrZF8J/Q+2H/ockgh5310nMp2xw8/d7g1JAD9orsyfDvvYnHKhSYQtp21q8VO1yfi8PqHIt5PZji3vpP1vTvRXPKngpAeYp4d9sw8QY7QOtv3XPtQ77ETVOVhspAgzpxPZpF9eqOkOxMStSCEk6B8+2ZWe3haq2U8Ws5Jlmn4qcbRI8CTeOF
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-client-secret
      namespace: argocd
    type: Opaque
