---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAz78LEccmrLY0632NcN+1URA8ukzKM+h/NByRRRGVEXbkkYrCF7sBbBplrJcKqxMh54HDxk1SXLeAKfbJVQnoF7ysqRqEe84XIe5qWIyAqeDx/5K+ivVbus1r7rYj2gyq+v+wiyXC2oOgb8aRKJ+VyNEO1u4VuQyqMo7Lw/tRyHg3rRQlxpVpEXyKeG7oyfP6kEyNSlr5kdZP9umHRnB/42cmuJ1odKlPTOZcQihCEufG2cYq+hBpQhnw3zKAu02otY9NdcsVjlo68woX/CcEwsIGiX2SfOHTKPukFiTBLyqO/W3aRe1X/7/Ndhd+QvoA8fc7SqLc8TCx4mGPeGSNgI4su5AsKBPGwkBumGXtJbhmBCIgHuJR+ed3R1BMXOazEjmLBySBGtYuf9xcbuv28xx9+IDC9IzZt3kVbkjcuJZioNXqWxkRwxG8Rrbt0Y8ppYjdO0wFI6tShIByl0BNpsP991LGlkLuHpwu1GelFIr5CfvZM64FFAfcfcD/av2A94KmJMZ5Lfwu0LryYLGx4jHUxrJgcO/gCuy5KsYtRRJSOMvYcBfo00qAKsHlL8IjXwtX/ff2ruJh6qJyUHGUlCN9/HjGcWER0oZjKBXeae4TiEmx1gDpFj6zzx8esAALzNs0Vv2injUT4PqW2P/kXumEP3OGZksrMF6/1140KMnKnniNsC3/w0qhIbatE2qMxrRN4JoQgS7MHZPXdm4tcAIkpm5U52iHnNvhSRbXUzB5PQ7KmgmClSw==
  template:
    metadata:
      annotations:
        app.kubernetes.io/part-of: argocd
      creationTimestamp: null
      name: github-client-secret
      namespace: argocd
    type: Opaque
