---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBoNgaTgjcJhn+24iN1wGttsQkENf2ng+jvo/PLuLdaw6GdFL3XJF2NfkKN7n7gd8ZIEubl1KdTsnbz0IPKWXFa9Un/6DuGWGoGo20D46HQmEbW+DxmdMKD5+3yMkEWCv73/WzNq/s2fqnW1+QSbU6GTnfB+mLMz7hi/9gUKzAN4eV1bwrrqeLDvAIEJKDuNqMmfiguZyaVR8/m+jia+cAw8NMU7UprM8Wet7w1r3+/ejc77TU6YsPcIOMYbyKBWeivG6+iOI42Ds8itIkxFmYKnb7xWb+ZFndi1GHK1569/pFqpJ1p0LpJvcyll1jqHrHwNna97uvZzPSWjFZ5aDUTNA+Y8oTyl7yEsQTf3GFnFqMTlkiuAI6aSflc1ykZG/NBamuEFrPyf1tT+CnqU9iFVwPx/16rAb8pIEMEwgUM8UwyKRZgyzYJezlB2Hu6X2+D3p9clPfidkKtB/xz3MVdKdc4MwAKBeF+5t75zq1MFIvaYuLMtkf/KpcG/2avOwiLCBQqLCNh35NT7RAFmkbKJuK10zHitbpZK+gppiJTb/5qVFLr6LohRB75HOrsSCTO5RcaD3T59to0eESPaW/I+qxYQ31a9XHBDSoxDk0P2YmHiIS8qv59Qb5DWK8XoTRbidB+9d9WpYHsLMlvLSDg8W8Al0ng2CTQDV0yxUlI6Z+kI+MXOhK3ZwaMAam/YitTEC/M3LnX0eScf53bsesupgkqHI1zjkiPMC2hH26ehwQZHsTsNkyw
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: github-client-secret
      namespace: argocd
    type: Opaque
