global:
  domain: argocd.mizuki.otaprv.ishiori.net

controller:
  replicas: 1

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
        - argocd.mizuki.otaprv.ishiori.net
        secretName: wild-mizuki-otaprv-ishiori-net-tls-secret
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns01-issuer
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    extraTls:
      - hosts:
        - grpc.argocd.mizuki.otaprv.ishiori.net
        secretName: grpc-argocd-mizuki-otaprv-ishiori-net-tls-secret
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

configs:
  params:
    server.insecure: "true"
  cm:
    exec.enabled: true