---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBx7gr7ntgIQNDyDNvFtOhdb6BjgauvsEnm/qLS16tbnxLVegwk2BoIcizrI2ZzaPYthP4GApNItk4GrGLsxuumK8MagG7WzZSp7aM3hqDutYWGJP6seZ7HQ3S2XSzNYVWjvbuUYUqj2dV1cGukol3ao7OT+i4umZU0vMjHyaN4R7lxC9cJtky0PlDbU0dviUI7J1kEUx3beEWTB15CTkZ9cpQopPKbUBDNZfgmeoJ79C8DmpMx1K1ojUzL49TpHaJVdws7nXfQ1FwCspaXpdkaES5yGpNInZkjCU2Nc5lYpgo7XXs1AB5B4MA8NNNR55Uv5NDKqxOGAq2+JPQupupA0MqAk1+9QVO8lojU90BPfTnm8mfZUMGNiqo8Ni3XD5graqC38IeXDlbo2rh5Zfn77LoHq77YXMj/umGNghzovQSM08DcH3ct83mPaaCsZ53wY5QMC2FgkMSNfq/BqjrHG5IpU7mgX0dYMG+mkGCdTHRDI7aEy/REc2pJmQAxwXU+ksQzqxOpEgSF/s0lTfd0HnE9xYxV8lJ32GykK9WiMUq4ei5D8sYLzW+Co0EJnfjFuSq0VFauhx5pZ8Jpek6s8umv1Y6mtetid0S6abX1rj7tuvDGIIaaHoqn1Nciy7O03wyhLgQBfcJTrbyr9oNHKhYw/Nu8SoikbaM0F+ApLv0aDoihbKn0rsp2yCpDqvLeDSLyLlvRtZqN+fQLXCF1/FybTQ89efn6zaPFgqU6WTu5RXhyB2+J
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
