---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBz4r8vSDOOduDXue0YNLSdvcMKXyu0WsrbJjYm6ks12lWVqWWTWdjxg9yZ3wlLWBwGZUzFDG26gVYlaLk99DszEHD4jfZZ4s7zqlYm9y9oEzW8EgQyDtdVhl1qSgu8GFG9VTmwCeGm2ThIH2+jy/gRn9TG7NvZcZfnaRP9kqpWB1SwlS6Utwwnrcw63+Yo772qQK2qSrWPJUrUlWKNkh5JC96C4mfTIBy5sCoSnGU0QtcsLjXMDvrg9dG74dX2n2oBit0F49sBTzLiTorTSiihvlDRta302SkX/ap/CL5S69uatztnBNELGidauP5hKI2ZVYUZnwEZ4pbdDA9y4GLP5QtFzURboJLKUX1aC6/duh4EKFTo3jDXJFmjyluzEwmpMdCAJngoKL/SDt5a5vCZtYBmIYUzEzE+7UdnqOsM4jPkYtZ2UUc5OnNm5MKoJDsph8eEryVwj1ymE/xbtQD7d6vwKhn6k/X7YfYeeY8hzjGvXQFIu3lHZXVjVBKPtMXn5PjBt4gfyV6zCZKxtubr1P/uT52ze2iIy1bzAPGF713A1/OC79UTib8vkzCtDCcH0YPQtzPfftzVyVDKP72zHYBBnt6wP9QSEEbNyGcZTNSwbyx4OOKDU5g8DjHVwl1Yz0vHr0IJBSRLPWg/2O5V297tx4Yb8NWxjJhjkdzkHM0ISp1EymBfHfs//bMx1aXaCyure+jTtNmoyitVH8wpgd02UkrJqDqUBZfXWTe587sysnv3Otsi
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
