---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBo1Ze/ZJDmZZk2OlvfWbWMvm1qWRj3fX9/HD7aSbPlqtXLrMpy5KOOQm7iSt+57mLqaeqUkZsRdp+5JYVhEXF+TR5lhnmNy7kJQEffJO/9WB9yTMctUqweJpseUiML1A0Bx8bRRyLyb+oIOGUr5+EMNE6mMkyVEjYJuoVIS6N1zqXGQtFUf9ngTuQpQ4Pwn0d4h8oSbCFF9g8LN578CguYE1G5DL74gplf5sf90W460PeMCOogJoRIhd5l2RdCH2k6MVzxVuFurAoldkU1i4t0GmWeaaNYP+1SaZRsR8EHGEKbDS4zlYXFYqnW2H95pCqxUZJs/2ON0ulgEqVJubx3a2MgwDQ1DxD15R/39PDpVsW0/07bDuNwmKZ3DnuUtLKtZNJh2zbCFExmWyfGvadyjAFs2ryQ5oYdj6EFhOrNYU+JBoSoUdpmqo0yDOAYGPBrcK/Mwb10HjpDIU/wJ/ltcZ3NpXZiXrDrEcQdSYFiBtncw2+XwuKyNaJCKXoC8NAAhEeNurhKTD1SyLym3buDCccImwSEi5u0QVCsKr+fcV3Dd0RZHEhK1ytrzRRoEbz4jZJxE1rB7x9jzqgqXw2mnQeS7zAb1Mv5zWbyZzjs2glpLMfwY7ltonjXYfwKgDImDNOcuYDlKAQj9HA8LIAepp64u8DvkieTNckH4npwl4IlBJTAREJjCG8w+JsL4IwMTBQgnRn7S2lSBBE6sO3XdVkHEvh/z8VQdmOMQGczmM1P3bqmwajL
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
