---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBSI3Xsjb47xnz2UbY9MmOAc4fxl2E2FVTcBuIi0xkm8m7QQDMqKUfq0opaRRvkaF1cE1TqHvhl/Ik4dCIPTdUCGQHcbvB4NKI10U5couXcJmD6tLbrHUeLO+L7y5bxRiYi3eOa66WeolRwpK1ox4nAdoic1F89nTlYueyOsbyk1WulaF8xoysV+53fWu807imIorwVoMdwCezAvACpTX0thkKIT3ArimN2+E3FRDFoK6jctiGeqSHXTqm+srZu3nr0bt93FW6fRwWEj7hjBZ5e/xTZ8QX/ij+sqDkadJg59krt1zksmlaCegEXYQ0nOg+yH/fYgXy9Tj3BNIwsi61Sur/PQcQUNPXrFzKe1hIFyB4q0Q6UiXuQJXcKeB3nHKRfrUAI+aC9+XMw73Bs/ffk2Qq92P9+Uv8xTuiRNrOApYXdol8Z70PK/9TjWHGFnHbxULTdum+qnLXWPKIa+2whkNhbT6WB5Cm2PVnITALYON17drJnHk100XWCSMU5IPIS3hDqvq1U7D40222TLZM3PlvtPfpoHEJCCzO/GkLcLIadRmCtpyuZfr6tBLqN7KxWz1qTCwG+VdLQ9Hhn3XkmAomy7OmbZAy95Rne+pMRvAfEMbPad4TPUC8n4YTdMKUB81M3zhRycW5/FRSEu9VtvWNXo+0hQPqM04lQC/i6tFARJvZ2x4Y6JKmIedWkyO5RAdU73FRglilKlov/HRu7ABCdTEBT4wHQwpfYv1r/bqaU0NwRmmqB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
