apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- ../../base
- helm-cert-manager.yaml
- cloudflare-api-token-secret.yaml
- clusterissuer.yaml
- certs/wild-mizuki-otaprv-ishiori-net.yaml
- certs/grpc-argocd-mizuki-otaprv-ishiori-net.yaml