---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-client-secret
  namespace: dex
spec:
  encryptedData:
    clientSecret: AgB97GFneLdQl9XvCUIAiCLcR1Hzld50vsUGbCQK99FXbTYaLjgPieQsqIDp8wQa7iniVK1igWdBczPHFC/sUu+sNft/9M75ftEQl8WAsAlcOw64pHt3JrukXNU/yV9vqluIsIU9+J6QUK5Cp9PZC5HJIrDikZfoCjSRgFCSceRZbXXbqP+5sNkDo0XlpCwFaPaLE+aiQu5xrmHnc4t4NH/wZt+bdiSE43cULXs3Vjs34GJZp36hYOv3+Dxc2RBMA7lUW7FKmJwGvnt1+5iLh/nHCBOXfu4xHAJnI6Z+DhwWsLhTdzkm+QyIb0UdQQbxhLKwKRJXeFifDOuLfNsmUlgqMItDc6/zEoy4Q5Y3a9J+Q24hLQtQwbt/Ns7/zvVxJnYY5m0kKpxRZrPkB1ST/aSs0sxfa426CdJAGWdZTsv9BwbPFzqtm6sbY37PpJOoL8uvfbJVLI4n+88NWKDK2EJx9QvOHt2H2GN7qy5K3s83KsiIxnptrkK9ft71X98VwijH4y96IFwvhiRh91eYR7FrOo2eSrTiP7Pyxpb7cVh7CfaStWH5SiUAWECnjKFRApbE2FJblCMD0iRpyQXwiMVsvJzAdviSV37t6H3vBPmT/AdH0+yJCtBXS53UOP1I4Ik07yM9lRK8O0SSJYk/3E8BLVKen+fYoGm/Rpv5ADtEC2wyVFt4nsGiMxPrsOgL2rNFKotccBCjTVnaYXKX1oe3lAlXrnWP2Qv/HSmkso/Xv5SaXXBI4t0m
  template:
    metadata:
      creationTimestamp: null
      name: github-client-secret
      namespace: dex
    type: Opaque
