config:
  issuer: https://dex.mizuki.otaprv.ishiori.net/dex
  storage:
    type: kubernetes
    config:
      inCluster: true
  staticClients:
  - id: dex-k8s-client
    redirectURIs:
    - 'http://localhost:5555/apis/auth/callback' # Local Development
    name: 'Dex Kubernetes Client'
    secretEnv: DEX_APP_CLIENT_SECRET
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: Ov23liilC9bcKy7smcTA
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: https://dex.mizuki.otaprv.ishiori.net/dex/callback
      orgs:
      - name: ishiori-net
        teams:
        - netwide-admin
        - mizuki-maintainer
        - mizuki-developer
      teamNameField: slug
      useLoginAsID: true

envVars:
  - name: GITHUB_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: github-client-secret
        key: clientSecret
  - name: DEX_APP_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: dex-client-secret
        key: dexAppSecret