---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-namespace-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
      revision: main
      files:
      - path: "cluster-utilities/argocd-managed/namespaces/cert-manager"