---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-namespace-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
      revision: main
      directories:
      - path: "cluster-utilities/argocd-managed/namespaces/cert-manager"
  template:
    spec:
      source:
        repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
        targetRevision: main
        path: "cluster-utilities/argocd-managed/namespaces/{{path.basename}}/patches/mizuki"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-app-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
      revision: main
      directories:
      - path: "cluster-utilities/argocd-managed/workloads/cert-manager"
  template:
    spec:
      source:
        repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
        targetRevision: main
        path: "cluster-utilities/argocd-managed/workloads/{{path.basename}}/patches/mizuki"
