apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- helm-argocd.yaml
- mizuki-cluster-app-project.yaml
- mizuki-cluster-namespace-project.yaml
- mizuki-app-project.yaml
- mizuki-namespace-project.yaml
