apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mizuki-cluster-namespace-project
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/reverseon/hanamizuki-k8s-cluster'
  sourceNamespaces:
  - 'argocd'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
  - group: ''
    kind: 'Namespace'
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'