global:
  domain: argocd.mizuki.otaprv.ishiori.net

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

configs:
  cm:
    exec.enabled: true