apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  source:
    helm:
      valueFiles:
      - ../../../base/helm-values/ingress-nginx.yaml
      - helm-value-patches/ingress-nginx.yaml