---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBQKj29FGtadg5j9/BCFI7UeXOWwBJBwYbI4/4SVAI3Lr9eKZBv44ku1U80/VUb1Y9dCJl0rraSZVGJ4Ic0UyywQxgMb1eR6jmCzRSYJtvWpkL2hFlhiO8BxVIHXbU6gIth3OLSv8tq/9JK+E11VxwQkifhG27iKsikWS1EdvGRuU92BbBEDOOlgoM6qbBxAeF8EWlxOE1CA3AffUlP21+9aetx93mb/W6UV/90/gv5PD3Nxn5RtIboZzxqUY0ihmpMfWQZWF8CmKlP3qJipGuLyEMz7OqPQY8/1fwTMtRG8lTDYAd5tA2cZfFWqme0x84vzqhs3ckKx9ReiLtxxjpQ6zeosQBS8ynxgW+xInoA9A81MSBf8+noa14cIPQyCKwYUEbzgLWTtDjcc+6nR/K0xTdoGT+WjuKbKClLA52eqneJU8IW3gwcaeYRYQaFofY95wUq5hXeMXvmDrOJP5w8tDJP7FPD6mB5TCk5Okk5RqgwiCQa8mR4xXzA5yuGbMYRF20EMDeaY/ti6QpdfWoAJ5kSuVDKCfRMmzwKb2vnVKevlpPIAdNooiqW7eFFht+wZ8AOU0ZP8nxO2xpeuVUDG/1hg2hGJzvw/MT2hC55KX4CbMF3tDo5eohPWWyQeTHZCUH6Dqm5ollW+7LAbpDaeh46IXO08B+bCi0kt0ivbTaDrKenGYOxx6z/PGJWuI7OJefcSU4UyJ4r7tp/WOQvDX8fkf9vEDIy1mqMGPoi0RcwE1TftBg5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
