apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ishiori-landing-page

resources:
- ../../base
- configmap.yaml
- service.yaml
- ingress.yaml

patchesStrategicMerge:
- deployment-patch.yaml