apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-app
  namespace: argocd
spec:
  source:
    path: cluster-utilities/argocd-managed/cluster-app/patches/mizuki
  syncPolicy:
    syncOptions:
    - ServerSideApply=true