---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: mizuki-cluster-app-project
  source:
    path: cluster-utilities/manual/ingress-nginx/patches/mizuki