---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCNdgmnKLFDNaYS19uhbKC82/0QrLOhkR0YbmQvOXoJxvi7nom6WRugWXVwyl4S0KBso2JG73Zkvid5D5pS2raD+RzPhQJ4SBqx8P0eMc5L1ShgxVC2qDrnU9pTbR7Tq4POHIQ5oK/gOZp5vM+tuLTY3y4oMEcYShHOQJDLenjIwPg8/WK1LrZc/OsvDLyz97eKJivGEYFgIerLpGHAai92iNjLoLTMzU3DpCfkmJX2eKPZ5RHZKhHbX/TTtDuPMiiiKqjPXMTks/hk8VYsX1VSxGBqMMi/7iWPOvtMC8KruDxhI3HfERyh063kgoUe0o10pBfxF8DwphISxNvupkRrWKuhTj/Kio7XAG9zo4aEzTZ6FmBCQ1bHS9x9MjjZKfjgbXO2AMKM5Bc4AGpm1zLNzokhoMXL21gm1lge06lq+by54KejLbA2hH51Ji1zhAWhcp9pWnU8OMVJVgPpY0YEiDlYuAZmhDZ4J62Zpm7s79DgbnB56oaK0zwpzXpzGhDCWQJT7H3P92lXwI0It5lMCgZBf6HG4dZ0lm0sli1CbvDgDq1FUfU6JoScyWE7AsatnAyXltvGcuhVMbQZt+tJtNS2Hn/QNDIpU/aWoBKc/OhBK/hpudKEk0Vt3SxjH1nABm6TyL1JcyaQCh+oEXpfG5ZFuCN11DKnrtYNPffm+UZqiES1DUw5/pxpOMxAVeGXo2Nu+rTPJwSKajE5Z9ZoS/ifUblxjUb1Wpzj/DQJ4Lxw5tp+TiIX
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
