---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-utilities-generator
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
      revision: main
      directories:
      - path: "cluster-utilities/cert-manager"
      - path: "cluster-utilities/reflector"
      - path: "cluster-utilities/ingress-nginx"
      - path: "cluster-utilities/metallb"
      - path: "cluster-utilities/sealed-secrets
  template:
    spec:
      project: mizuki-cluster-utilities-project
      source:
        repoURL: https://github.com/reverseon/hanamizuki-k8s-cluster.git
        targetRevision: main
        path: "cluster-utilities/{{path.basename}}/patches/mizuki"
      destination:
        namespace: mizuki-cluster-utilities # not managed by ArgoCD
