apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hana-app-project
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/reverseon/hanamizuki-k8s-cluster'
  sourceNamespaces:
  - 'argocd'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  clusterResourceBlacklist:
  - group: '*'
    kind: '*'