apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- helm-argocd.yaml
- github-client-secret.yaml
- hana-cluster-utilities-project.yaml
- hana-app-project.yaml
- hana-namespace-project.yaml
